# Mod
mod_id      = placewatchdebug
mod_name    = PlaceWatchDebug
mod_version = 1.0.0
mod_group   = deliciousbread481

# Environment (Cleanroom / Forge 1.12.2)
mc_version      = 1.12.2
forge_version   = 14.23.5.2860
mappings        = stable_39

# Mixin
mixin_version = 0.7.11-SNAPSHOT

org.gradle.jvmargs = -Xmx3G
org.gradle.daemon  = false